name: open_media_server_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  media_kit_tv: ^0.0.1
  http: ^1.2.2
  device_info_plus: ^11.0.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.2
  oauth2_client: ^3.3.0
  random_string: ^2.3.1
  qr_flutter: ^4.1.0
  icons_plus: ^5.0.0
  alphabet_scrollbar: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/AppImage/myapp.png